language: node_js

sudo: false

node_js:
  - "stable"
  - "0.12"
  - "0.10"

before_install:
  - npm i npm@2 -g # Update to latest npm 2.x

script:
  - npm outdated --depth 0
  - npm run-script test-travis
