[package]
name = "scriptplan-core"
version = "1.0.0"
authors = ["Patrick Shaw <mail@patrickshaw.me>"]
edition = "2021"

[dependencies]
conch-runtime = { git = "https://github.com/ipetkov/conch-runtime" }
async-trait = { version = "0.1.50" }
async-recursion = { version = "0.3.2" }
futures = { version = "0.3.15" }
