[package]
name = "scriptplan-core"
version = "2.0.0"
authors = ["Patrick Shaw <mail@patrickshaw.me>"]
edition = "2018"
license = "MIT"
description = "Core schema for creating programatic script plans"

[dependencies]
async-trait = { version = "0.1.50" }
async-recursion = { version = "0.3.2" }
futures = { version = "0.3.15" }
