install-osx:brew:
  script: /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
install-osx:node:
  script: |
    curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.38.0/install.sh | bash
    nvm install
    nvm use
    npm install --global yarn
    yarn install
install-osx:rust:
  script: |
    brew install llvm
    ln -s /usr/local/opt/llvm/bin/lld-link ~/bin/link.exe

    curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh

    rustup target add x86_64-pc-windows-gnu
    rustup target add x86_64-apple-darwin

install-osx:
  script: |
    ./$0 install-osx:brew
    ./$0 install-osx:node
    ./$0 install-osx:rust
    ./$0 create-ssl-certificate-osx

# Note: If you've broken scriptplan then you either rollback then rollback to the old scriptplan file or try run this script directly in the terminal
recompile-scriptplan:
  script: |
    cargo build --release --bins --target x86_64-pc-windows-gnu --package scriptplan
    cargo build --release --bins --target x86_64-apple-darwin --package scriptplan
    mv ./target/x86_64-pc-windows-gnu/release/scriptplan.exe ./scriptplan.exe
    mv ./target/x86_64-apple-darwin/release/scriptplan ./scriptplan

node-base:
  script: node --require ./.pnp.js --require=./transpile-at-runtime.js --require=./original-code-require-override.ts
# FIXME: Remove ./$0
run:buildplan:
  script: ./$0 node-base buildplan.ts

# FIXME: Remove ./$0
format:javascript: run:buildplan format
format:rust:
  script: cargo fmt
# FIXME: Remove ./$0
format:
  script: ./$0 format:javascript && ./$0 format:rust

format-staged:javascript: run:buildplan format-staged
# FIXME: Remove ./$0
format-staged: ./$0 "format-staged:javascript" && ./$0 format:rust

test: run:buildplan test
clean: run:buildplan clean
transpile: run:buildplan transpile
build: run:buildplan build
build-all: run:buildplan build-all
watch: run:buildplan watch
writeme: run:buildplan writeme
webpack: run:buildplan webpack
serve: run:buildplan serve
serve:my-resume: run:buildplan serve --name='my-resume'
serve:page-breaker: run:buildplan serve --name='page-breaker'
serve:genetic-sequence-analysis-app: run:buildplan serve --name='genetic-sequence-analysis-app'
serve:particle-sensor-app: run:buildplan serve --name='particle-sensor-app'
serve:spot-welder-app: run:buildplan serve --name='spot-welder-app'
precommit: run:buildplan precommit
update-yarn:
  script: yarn set version berry && yarn add @yarnpkg/pnpify --dev && yarn install && yarn pnpify --sdk
create-ssl-certificate-osx:
  script: openssl req -x509 -config localhost.cnf -new -nodes -keyout localhost.key -out localhost.crt
