compressionLevel: mixed

enableGlobalCache: false

nodeLinker: node-modules

pnpFallbackMode: dependencies-only

pnpMode: strict

preferInteractive: false

preferReuse: true

yarnPath: .yarn/releases/yarn-4.0.2.cjs
