nodeLinker: node-modules

plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-constraints.cjs
    spec: "@yarnpkg/plugin-constraints"

pnpFallbackMode: dependencies-only

pnpMode: strict

preferInteractive: false

yarnPath: .yarn/releases/yarn-3.2.0.cjs
