plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-version.cjs
    spec: "@yarnpkg/plugin-version"

pnpFallbackMode: all

pnpMode: loose

preferDeferredVersions: true

yarnPath: .yarn/releases/yarn-2.1.1.cjs
