plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-version.cjs
    spec: "@yarnpkg/plugin-version"
  - path: .yarn/plugins/@yarnpkg/plugin-interactive-tools.cjs
    spec: "@yarnpkg/plugin-interactive-tools"

pnpFallbackMode: none

pnpMode: strict

preferDeferredVersions: true

preferInteractive: true

yarnPath: .yarn/releases/yarn-2.1.1.cjs
