plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-version.js
    spec: "@yarnpkg/plugin-version"

pnpFallbackMode: all

pnpMode: loose

preferDeferredVersions: true

yarnPath: .yarn/releases/yarn-2.0.0-rc.36.cjs
