[package]
name = "scriptplan-bash"
version = "3.0.0"
authors = ["Patrick Shaw <mail@patrickshaw.me>"]
edition = "2021"
license = "MIT"
description = "Use Bash as your scriptplan command parser"

[dependencies]
yaml-rust = "0.4.5"
shellwords = "1.1.0"
async-trait = "0.1.50"
futures = "0.1.14"
scriptplan-core = { path="../core", version = "3.0.0" }
tokio = { version = "1.1.2", features = ['process', 'rt', 'io-util'] }
