[package]
name = "scriptplan-bash"
version = "1.0.0"
authors = ["Patrick Shaw <mail@patrickshaw.me>"]
edition = "2021"

[dependencies]
yaml-rust = "0.4.5"
conch-parser = { version = "0.1" }
conch-runtime = { git = "https://github.com/ipetkov/conch-runtime" }
shellwords = { version = "1.1.0" }
async-trait = { version = "0.1.50" }
futures = { version = "0.3.15" }
scriptplan-core = { path="../core", version = "1.0.0" }
