language: node_js

node_js:
  - "6"
  - "8"
  - "10"
  - "node"

os:
  - linux
  - osx
  - windows

cache:
  directories:
    - "node_modules"

after_success: if [[ "$TRAVIS_OS_NAME" != 'windows' ]]; then npm run coverage; fi
