[package]
name = "lifepo4-cell-charger"
version = "0.1.0"
authors = ["Patrick Shaw <mail@patrickshaw.me>"]
edition = "2018"
publish = false

[dependencies]
panic-halt = "0.2.0"
nb = "0.1.2"
ufmt = "0.1.0"
embedded-hal = "0.2.3"

[dependencies.arduino-hal]
git = "https://github.com/rahix/avr-hal"
rev = "ac72adbe6db8900c41681b759ff62a11f2915916"
features = ["arduino-mega2560"]

[dependencies.avr-hal-generic]
git = "https://github.com/rahix/avr-hal"
rev = "ac72adbe6db8900c41681b759ff62a11f2915916"

# TODO: Copied from Arduino, should probably not be just called "dev"/"release"
[profile.dev]
panic = "abort"
lto = true
opt-level = "s"

[profile.release]
panic = "abort"
codegen-units = 1
debug = true
lto = true
opt-level = "s"
