[[bin]]
name = "scriptplan"
path = "src/main.rs"

[package]
name = "scriptplan-cli"
version = "5.1.0"
authors = ["Patrick Shaw <mail@patrickshaw.me>"]
edition = "2021"
license = "MIT"
description = "A script CLI builder"

[dependencies]
ansi_term = "0.12.1"
clap = "3.0.14"
tokio = { version = "1.1.2", features = ["fs", "io-util", "process", "macros", 'rt-multi-thread'] }
shellwords = { version = "1.1.0" }
async-trait = { version = "0.1.50" }
async-recursion = { version = "0.3.2" }
futures = { version = "0.3.15" }
scriptplan-bash = { path="../bash", version = "3.0.0" }
