[package]
name = "scriptplan-lang-utils"
version = "1.0.0"
authors = ["Patrick Shaw <mail@patrickshaw.me>"]
edition = "2021"
license = "MIT"
description = "Language utilities for Scriptplan languages"
