[package]
name = "reconcile-array"
version = "0.1.0"
authors = ["Patrick Shaw <mail@patrickshaw.me>"]
edition = "2021"
publish = false

[dependencies]
reconcilable-trait = { path="../reconcilable-trait", version = "0.1.0" }
