name: JavaScript modules integrity check

on: 
  pull_request:
    paths:
    - '**/package.json'
    - 'yarn.lock'
    - '.yarn/**'

env:
  NODE_ENV: production

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Use Node 14.x
      uses: actions/setup-node@v1
      with:
        node-version: 14.x
    - run: yarn install --check-cache
 