name: JavaScript tests

on: [push, pull_request]

env:
  NODE_ENV: production

jobs:
  test:
    strategy:
      matrix:
        os:
          -
            id: ubuntu-latest
            scriptplan-path: ./scriptplan-linux-gnu
          -
            id: macos-latest
            scriptplan-path: ./scriptplan
          -
            id: windows-latest
            scriptplan-path: .\scriptplan.exe
        node-version: [14.x]

    runs-on: ${{ matrix.os.id }}

    steps:
    - uses: actions/checkout@v2
    - name: Use Node ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - run: yarn install --immutable
    - run: ${{matrix.os.scriptplan-path}} build
    - run: ${{matrix.os.scriptplan-path}} test
